# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        large language model: 1
        LLM: 1

        syntax: 1
        linguistics: 1
        linguistic: 1
        targeted syntactic evaluation: 1
        syntactic: 1
        semantics: 1
        parsing: 1
        cognitive modeling: 1
        language acquisition: 1
        grammar: 1
        eye-tracking: 1
        reading time: 1
        brain: 1


# 通知の閾値
score_threshold: 2
